export const CREATE_CHAT: "CREATE_CHAT" = "CREATE_CHAT";
export const DELETE_CHAT: "DELETE_CHAT" = "DELETE_CHAT";
export const ADD_CHAT: "ADD_CHAT" = "ADD_CHAT";
export const GET_CHATS: "GET_CHATS" = "GET_CHATS";
export const SET_CHATS: "SET_CHATS" = "SET_CHATS";
export const CHATS_SET_IS_LOADING: "CHATS_SET_IS_LOADING" =
  "CHATS_SET_IS_LOADING";
