export const CREATE_CHAT: "CREATE_CHAT" = "CREATE_CHAT";
export const DELETE_CHAT: "DELETE_CHAT" = "DELETE_CHAT";
export const ADD_CHAT: "ADD_CHAT" = "ADD_CHAT";
export const CHANGE_CHAT_NAME: "CHANGE_CHAT_NAME" = "CHANGE_CHAT_NAME";
export const GET_CHATS: "GET_CHATS" = "GET_CHATS";
export const GET_MESSAGES: "GET_MESSAGES" = "GET_MESSAGES";
export const SET_MESSAGES: "SET_MESSAGES" = "SET_MESSAGES";
export const ADD_MESSAGE: "ADD_MESSAGE" = "ADD_MESSAGE";
export const SET_CHATS: "SET_CHATS" = "SET_CHATS";
export const SET_ROOM_USERS: "SET_ROOM_USERS" = "SET_ROOM_USERS";
export const CHATS_SET_IS_LOADING: "CHATS_SET_IS_LOADING" =
  "CHATS_SET_IS_LOADING";

export const CHAT_CONNECT: "CHAT_CONNECT" = "CHAT_CONNECT";
export const CHAT_DISCONNECT: "CHAT_DISCONNECT" = "CHAT_DISCONNECT";
