export const ADD_ACTION: "ADD_ACTION" = "ADD_ACTION";
export const ADD_DELAY_ACTION: "ADD_DELAY_ACTION" = "ADD_DELAY_ACTION";
export const REGISTER_ACCOUNT_ACTION: "REGISTER_ACCOUNT_ACTION" =
  "REGISTER_ACCOUNT_ACTION";
export const LOGIN_ACCOUNT_ACTION: "LOGIN_ACCOUNT_ACTION" =
  "LOGIN_ACCOUNT_ACTION";
export const LOGOUT_ACCOUNT_ACTION: "LOGOUT_ACCOUNT_ACTION" =
  "LOGOUT_ACCOUNT_ACTION";
export const AUTORIZATION_SET_IS_LOADING: "AUTORIZATION_SET_IS_LOADING" =
  "AUTORIZATION_SET_IS_LOADING";
