export const CHAT_RECIVE_MESSAGE: "CHAT_RECIVE_MESSAGE" = "CHAT_RECIVE_MESSAGE";
export const CHAT_SEND_MESSAGE: "CHAT_SEND_MESSAGE" = "CHAT_SEND_MESSAGE";
export const CHAT_JOIN_ROOM: "CHAT_JOIN_ROOM" = "CHAT_JOIN_ROOM";
export const CHAT_LEAVE_CHAT: "CHAT_LEAVE_CHAT" = "CHAT_LEAVE_CHAT";
export const CHAT_USER_CONNECTED: "CHAT_USER_CONNECTED" = "CHAT_USER_CONNECTED";
export const CHAT_USER_DISCONNECTED: "CHAT_USER_DISCONNECTED" =
  "CHAT_USER_DISCONNECTED";
