export const AVATARS_CREATE_AVATAR: "AVATARS_CREATE_AVATAR" =
  "AVATARS_CREATE_AVATAR";
export const AVATARS_CHANGE_AVATAR: "AVATARS_CHANGE_AVATAR" =
  "AVATARS_CHANGE_AVATAR";
export const AVATARS_GET_AVATARS: "AVATARS_GET_AVATARS" = "AVATARS_GET_AVATARS";
export const AVATARS_FORM_NAME_CHANGE: "AVATARS_FORM_NAME_CHANGE" =
  "AVATARS_FORM_NAME_CHANGE";
export const AVATARS_FORM_SRC_CHANGE: "AVATARS_FORM_SRC_CHANGE" =
  "AVATARS_FORM_SRC_CHANGE";
export const AVATARS_SET_AVATARS: "AVATARS_SET_AVATARS" = "AVATARS_SET_AVATARS";
export const AVATARS_SET_IS_LOADING: "AVATARS_SET_IS_LOADING" =
  "AVATARS_SET_IS_LOADING";
