export const REGISTER_ACCOUNT_ACTION: "REGISTER_ACCOUNT_ACTION" =
  "REGISTER_ACCOUNT_ACTION";
export const LOGIN_ACCOUNT_ACTION: "LOGIN_ACCOUNT_ACTION" =
  "LOGIN_ACCOUNT_ACTION";
export const LOGOUT_ACCOUNT_ACTION: "LOGOUT_ACCOUNT_ACTION" =
  "LOGOUT_ACCOUNT_ACTION";
export const AUTORIZATION_SET_IS_LOADING: "AUTORIZATION_SET_IS_LOADING" =
  "AUTORIZATION_SET_IS_LOADING";
export const AUTORIZATION_PASSWORD_CHANGE: "AUTORIZATION_PASSWORD_CHANGE" =
  "AUTORIZATION_PASSWORD_CHANGE";
export const AUTORIZATION_NAME_CHANGE: "AUTORIZATION_NAME_CHANGE" =
  "AUTORIZATION_NAME_CHANGE";
export const AUTHORIZATION_SET_IS_AUTHORIZED: "AUTHORIZATION_SET_IS_AUTHORIZED" =
  "AUTHORIZATION_SET_IS_AUTHORIZED";
export const AUTHORIZATION_CHECK_AUTH: "AUTHORIZATION_CHECK_AUTH" =
  "AUTHORIZATION_CHECK_AUTH";
